# Generated by Django 4.2.6 on 2023-11-23 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_join',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'user with that username already exist'}, help_text='Required. 30 Character or fewer Starting with latter', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_\\.]+$')], verbose_name='user name'),
        ),
    ]
