# Generated by Django 4.2.6 on 2023-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='user must be active, un select this instead deletig accunt', verbose_name='active'),
        ),
    ]
